### ISSUE TITLE
Separate Interface Package?

### ISSUE THREAD

**Issue by jakejohns** [zendframework/zend-permissions-acl#16]
Does anyone share my desire to separate the interfaces here into their own
package?

I feel like I want to be able to write packages that required something like
`zendframework/permissions-acl-interface` rather than the whole implementation.

This way, for example, I could write an authentication package where identity
objects implement `RoleInterface`, or make some domain package where objects
implement `ResourceInterface` to facilitate integration but not require
installation of Zend\Permissions\Acl if one desires some alternative
implementation. Something similar to what is done with [Aura\Payload](https://github.com/auraphp/Aura.Payload) and
[Aura\Payload_Interface](https://github.com/auraphp/Aura.Payload_Interface).

Thoughts?

**Comment by weierophinney** [comment]
zend-permissions-acl is meant to provide:
- Basic interfaces for representing access control lists
- A basic, extendable system implementing ACLs

We do not currently see the value in separating them, particularly considering that the LOC amount to only ~1k lines, with only ~300 lines of logic. Removing the implementation just increases the number of dependencies for those that _do_ want the implementation at this point.

We may revisit this in the future (we separated interface-providing packages from implementations in Expressive), but for now, we have no plans to do similarly with the component packages.

**Comment by jakejohns** [comment]
Thanks for the response!
Keep up the excellent work!
